# fly.toml app configuration file generated for ff14-gear-allocation-bot on 2025-10-07T18:37:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ff14-gear-allocation-bot'
primary_region = 'nrt'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
