app = "ff14-gear-allocation-bot"
primary_region = "nrt"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
